name: Trigger Repo 2 Pipeline
on:
  push:
    paths:
      - “build.yaml”
    branches:
      - main  # Change to your primary branch
jobs:
  trigger-mobility-specification:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo 2 Workflow
        run: |
          curl -X POST -H “Authorization: token ${{ secrets.PAT }}” \
               -H “Accept: application/vnd.github.v3+json” \
               https://api.github.com/repos/mofahsan/api-service-generator/actions/workflows/generator.yml/dispatches \
               -d ‘{“ref”:“main”}’
